#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/overnight/common.sh
source "${SCRIPT_DIR}/common.sh"

: "${ISSUE_NUMBER:?ISSUE_NUMBER is required}"

plan_path="${PLAN_DIR}/plan-${ISSUE_NUMBER}.md"
metadata_path="${PLAN_DIR}/plan-metadata-${ISSUE_NUMBER}.json"
log_path="${LOG_DIR}/claude-plan-${ISSUE_NUMBER}.log"

planning_prompt=$(
  cat <<EOF
You are Claude Code operating as the overnight planner for /workspaces/dev-openclaw.

Task source:
- Issue #${ISSUE_NUMBER}
- Title: ${ISSUE_TITLE:-}
- Labels JSON: ${ISSUE_LABELS_JSON:-[]}

Issue body:
${ISSUE_BODY:-}

Requirements:
- Produce an implementation plan only. Do not modify repository files.
- Follow AGENTS.md and .agent/PLANS.md.
- For shell usage, only ls and cat are allowed without extra approval.
- Any other command must go through ${REPO_ROOT}/scripts/overnight/command-gate.sh.
- Return a concise ExecPlan in markdown that another agent can implement directly.
EOF
)

if [[ "${DRY_RUN:-false}" == "true" ]]; then
  cat > "${plan_path}" <<EOF
# Issue #${ISSUE_NUMBER} Overnight Plan

## Summary

Dry-run placeholder plan generated by the Claude planner path.

## Steps

1. Read the issue and inspect relevant files.
2. Implement the required change with tests.
3. Run approved verification commands or request approval for others.
EOF
  jq -n \
    --arg planner "claude" \
    --arg plan_path "${plan_path}" \
    --arg status "success" \
    --argjson fallback_used false \
    '{planner: $planner, plan_path: $plan_path, status: $status, fallback_used: $fallback_used}' \
    > "${metadata_path}"
  write_output "plan_path" "${plan_path}"
  write_output "metadata_path" "${metadata_path}"
  write_output "planner" "claude"
  exit 0
fi

if ! command -v claude >/dev/null 2>&1; then
  log "claude command not available; planner fallback required"
  exit 42
fi

set +e
claude -p "${planning_prompt}" \
  --yes \
  --allowedTools "Read,Write,Edit,Glob,Grep,Bash(ls *),Bash(cat *),Bash(${REPO_ROOT}/scripts/overnight/command-gate.sh *)" \
  --max-turns 50 \
  > "${plan_path}" 2> "${log_path}"
status=$?
set -e

if [[ ${status} -ne 0 ]]; then
  if grep -Eqi 'rate limit|usage limit|subscription|quota|too many requests' "${log_path}"; then
    log "claude planner hit a retryable limit"
    exit 42
  fi
  exit "${status}"
fi

if [[ ! -s "${plan_path}" ]]; then
  log "claude planner produced an empty plan"
  exit 43
fi

jq -n \
  --arg planner "claude" \
  --arg plan_path "${plan_path}" \
  --arg status "success" \
  --argjson fallback_used false \
  '{planner: $planner, plan_path: $plan_path, status: $status, fallback_used: $fallback_used}' \
  > "${metadata_path}"

write_output "plan_path" "${plan_path}"
write_output "metadata_path" "${metadata_path}"
write_output "planner" "claude"
