#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/overnight/common.sh
source "${SCRIPT_DIR}/common.sh"

: "${ISSUE_NUMBER:?ISSUE_NUMBER is required}"

plan_path="${PLAN_DIR}/plan-${ISSUE_NUMBER}.md"
metadata_path="${PLAN_DIR}/plan-metadata-${ISSUE_NUMBER}.json"

planning_prompt=$(
  cat <<EOF
You are Codex operating as the overnight fallback planner for /workspaces/dev-openclaw.

Task source:
- Issue #${ISSUE_NUMBER}
- Title: ${ISSUE_TITLE:-}
- Labels JSON: ${ISSUE_LABELS_JSON:-[]}

Issue body:
${ISSUE_BODY:-}

Rules:
- Produce an implementation plan only. Do not modify files.
- Follow AGENTS.md and .agent/PLANS.md.
- Treat file CRUD inside the devcontainer workspace as allowed, but do not perform file writes in this planning task.
- Only ls and cat may be run without approval.
- Any other shell command must be requested through ${REPO_ROOT}/scripts/overnight/command-gate.sh.
- Return markdown only.
EOF
)

if [[ "${DRY_RUN:-false}" == "true" ]]; then
  cat > "${plan_path}" <<EOF
# Issue #${ISSUE_NUMBER} Overnight Plan

## Summary

Dry-run placeholder plan generated by the Codex fallback planner path.

## Steps

1. Inspect issue context.
2. Update the relevant code and tests.
3. Use approved commands only, requesting approval when required.
EOF
else
  require_command codex
  codex exec \
    -C "${REPO_ROOT}" \
    -s read-only \
    -o "${plan_path}" \
    "${planning_prompt}"
fi

jq -n \
  --arg planner "codex" \
  --arg plan_path "${plan_path}" \
  --arg status "success" \
  --argjson fallback_used true \
  '{planner: $planner, plan_path: $plan_path, status: $status, fallback_used: $fallback_used}' \
  > "${metadata_path}"

write_output "plan_path" "${plan_path}"
write_output "metadata_path" "${metadata_path}"
write_output "planner" "codex"
